### ISSUE TITLE
Trigger animation when component is visible to users

### ISSUE THREAD

**Issue by frusciante189** [suyalcinkaya/gauge#17]
Currently, the animations are triggered immediately when the page loads. It could be enhanced by triggering animations only when the elements are actually visible to the users. This would improve user experience.

**Comment by suyalcinkaya** [comment]
I tried to tackle this including adding a rerendering button to trigger the rerendering of the component manually, but I couldn't find a proper way to do so quickly. I'll spend more time on that when I have the opportunity. Please feel free to submit a PR if you already have the solution 🤞
